# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_session.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 240)
        Form.setMinimumSize(QtCore.QSize(400, 240))
        Form.setMaximumSize(QtCore.QSize(400, 240))
        self.pushButton_Cancel = QtWidgets.QPushButton(Form)
        self.pushButton_Cancel.setGeometry(QtCore.QRect(310, 170, 75, 23))
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 399, 77))
        font = QtGui.QFont()
        font.setFamily("Seb Neue")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.pushButton_Ok = QtWidgets.QPushButton(Form)
        self.pushButton_Ok.setGeometry(QtCore.QRect(220, 170, 75, 23))
        self.pushButton_Ok.setObjectName("pushButton_Ok")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(0, 80, 399, 74))
        font = QtGui.QFont()
        font.setFamily("Seb Neue")
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("margin: 20px;")
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Add session"))
        self.pushButton_Cancel.setText(_translate("Form", "Cancel"))
        self.label.setText(_translate("Form", "Name of the session"))
        self.pushButton_Ok.setText(_translate("Form", "OK"))
