# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mail_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MailWindow(object):
    def setupUi(self, MailWindow):
        MailWindow.setObjectName("MailWindow")
        MailWindow.resize(864, 888)
        self.verticalLayoutWidget = QtWidgets.QWidget(MailWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 861, 881))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(MailWindow)
        QtCore.QMetaObject.connectSlotsByName(MailWindow)

    def retranslateUi(self, MailWindow):
        _translate = QtCore.QCoreApplication.translate
        MailWindow.setWindowTitle(_translate("MailWindow", "Mail"))
