# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(415, 395)
        Form.setMinimumSize(QtCore.QSize(415, 395))
        Form.setMaximumSize(QtCore.QSize(415, 395))
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 411, 391))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_Save_Settings = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Save_Settings.setObjectName("pushButton_Save_Settings")
        self.gridLayout.addWidget(self.pushButton_Save_Settings, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.groupBox_Theme = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.groupBox_Theme.setObjectName("groupBox_Theme")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_Theme)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 381, 71))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_LightTheme = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_LightTheme.setObjectName("radioButton_LightTheme")
        self.horizontalLayout_2.addWidget(self.radioButton_LightTheme)
        self.radioButton_DarkTheme = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_DarkTheme.setObjectName("radioButton_DarkTheme")
        self.horizontalLayout_2.addWidget(self.radioButton_DarkTheme)
        self.gridLayout.addWidget(self.groupBox_Theme, 1, 0, 1, 2)
        self.groupBox_Language = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.groupBox_Language.setObjectName("groupBox_Language")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_Language)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 381, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_RU = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_RU.setObjectName("radioButton_RU")
        self.horizontalLayout.addWidget(self.radioButton_RU)
        self.radioButton_EN = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_EN.setObjectName("radioButton_EN")
        self.horizontalLayout.addWidget(self.radioButton_EN)
        self.gridLayout.addWidget(self.groupBox_Language, 0, 0, 1, 2)
        self.groupBox_Save = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.groupBox_Save.setObjectName("groupBox_Save")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_Save)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 381, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_Save_Path = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_Save_Path.setObjectName("lineEdit_Save_Path")
        self.horizontalLayout_3.addWidget(self.lineEdit_Save_Path)
        self.pushButton_Browse = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_Browse.setObjectName("pushButton_Browse")
        self.horizontalLayout_3.addWidget(self.pushButton_Browse)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.gridLayout.addWidget(self.groupBox_Save, 2, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Settings"))
        self.pushButton_Save_Settings.setText(_translate("Form", "Save settings"))
        self.groupBox_Theme.setTitle(_translate("Form", "Theme"))
        self.radioButton_LightTheme.setText(_translate("Form", "Light Theme"))
        self.radioButton_DarkTheme.setText(_translate("Form", "Dark Theme"))
        self.groupBox_Language.setTitle(_translate("Form", "Language"))
        self.radioButton_RU.setText(_translate("Form", "Russian"))
        self.radioButton_EN.setText(_translate("Form", "English"))
        self.groupBox_Save.setTitle(_translate("Form", "Save"))
        self.pushButton_Browse.setText(_translate("Form", "Browse"))
